# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fb_graph}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nov matake"]
  s.date = %q{2010-04-24}
  s.description = %q{Facebook Graph API library for Ruby}
  s.email = %q{nov@matake.jp}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "fb_graph.gemspec",
     "lib/fb_graph.rb",
     "lib/fb_graph/connections.rb",
     "lib/fb_graph/connections/likes.rb",
     "lib/fb_graph/connections/picture.rb",
     "lib/fb_graph/connections/statuses.rb",
     "lib/fb_graph/node.rb",
     "lib/fb_graph/page.rb",
     "lib/fb_graph/status.rb",
     "lib/fb_graph/user.rb",
     "spec/connections/likes_spec.rb",
     "spec/connections/picture_spec.rb",
     "spec/connections/statuses_spec.rb",
     "spec/fake_json/pages/statuses/platform_private.json",
     "spec/fake_json/pages/statuses/platform_public.json",
     "spec/fake_json/users/arjun_private.json",
     "spec/fake_json/users/arjun_public.json",
     "spec/fake_json/users/likes/arjun_private.json",
     "spec/fake_json/users/likes/arjun_public.json",
     "spec/fake_json/users/statuses/arjun_private.json",
     "spec/fake_json/users/statuses/arjun_public.json",
     "spec/fb_graph/node_spec.rb",
     "spec/fb_graph/user_spec.rb",
     "spec/fb_graph_spec.rb",
     "spec/helpers/fake_json_helper.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nov/fb_graph}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Facebook Graph API library for Ruby}
  s.test_files = [
    "spec/connections/likes_spec.rb",
     "spec/connections/picture_spec.rb",
     "spec/connections/statuses_spec.rb",
     "spec/fb_graph/node_spec.rb",
     "spec/fb_graph/user_spec.rb",
     "spec/fb_graph_spec.rb",
     "spec/helpers/fake_json_helper.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end

